class Config:
    MYSQL_HOST = 'localhost'
    MYSQL_USER = 'root'
    MYSQL_PASSWORD = 'Gondoliere01_'
    MYSQL_DB = 'jetair'
    # MYSQL_HOST = 'localhost'
    # MYSQL_USER = 'root'
    # # MYSQL_PASSWORD = 'Gondoliere01_'
    # MYSQL_PASSWORD = 'SQL46lock?'
    # MYSQL_DB = 'jetair'